
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../../node_modules/@fortawesome/fontawesome-free/css/all.min.css";
import "./globals.css";
import Navbar from "@/app/_components/Navbar/Navbar";
import { Toaster } from "@/components/ui/sonner";
import { SessionProvider } from "next-auth/react";
import MySessionProviders from "./_providers/MySessionProviders";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

//   const metadata: Metadata = {
//   title : "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <head>

 
        
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>

          
        
        <MySessionProviders>

        <Navbar/>
            {children}
        <Toaster />

        </MySessionProviders>
         
        
       
      
      </body>
    </html>
  );
}
